# Generated by Django 4.1.1 on 2022-09-30 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobilio_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(max_length=200, verbose_name='Marke')),
                ('modelis', models.CharField(max_length=200, verbose_name='Modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=200, verbose_name='Valstyvinis_NR')),
                ('vin_kodas', models.IntegerField(verbose_name='VIN kodas')),
                ('klientas', models.CharField(max_length=200, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.automobilio_modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Paslaugos pavadinimas', max_length=200, verbose_name='Pavadinimas')),
                ('kaina', models.IntegerField(help_text='Paslaugos kaina', verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('suma', models.IntegerField(verbose_name='Suma')),
                ('automobilis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobilis')),
            ],
        ),
    ]
